GLOBAL stack_create

MAP_GROWSDOWN	EQU 0x0100
MAP_ANONYMOUS	EQU 0x0020
MAP_PRIVATE	    EQU 0x0002
PROT_READ	    EQU 0x1
PROT_WRITE	    EQU 0x2
PROT_EXEC	    EQU 0x4

SECTION .text
stack_create:
	MOV rsi, rdi
	XOR rdi, rdi
	MOV rdx, PROT_WRITE | PROT_READ
	MOV r10, MAP_ANONYMOUS | MAP_PRIVATE | MAP_GROWSDOWN
	MOV r8, -1
	XOR r9, r9
	MOV rax, 0x09
	SYSCALL
	RET
